easy_admin:
  site_name: "Panel Admin Leboncoin"
  design:
    menu:
      - { label: 'Accueil', route: 'leboncoin_index', icon: 'home' }
      - { entity : 'Annonces', icon : 'newspaper' }
      - { entity: 'User', icon : 'user' }
  entities:
    Annonces:
      class: App\Entity\Annonces
      list:
        fields:
          - author
          - title
          - content
          - { property: 'photos', type: 'image' , base_path : '/uploads/annoncesPictures'}
          - created_on
      form:
        fields:
          - title
          - content
          - price
          - { property: 'photosFile', type: 'vich_image'}
    User:
      class: App\Entity\User
      list:
        fields:
          - username
          - annonces
          - roles
          - { property: 'avatar', type: 'image' , base_path : '/uploads/UserPictures'}
      form:
        fields:
          - username
          - password
          - annonces
          - { property: 'roles' , type: 'collection', permission: 'ROLE_SUPER_ADMIN' }
          - { property: 'avatarFile', type: 'vich_image'}
      new : 
        fields:
          - password
          - '-annonces'