vich_uploader:
    db_driver: orm

    mappings:
       user_avatar:
        uri_prefix: /uploads/UserPictures
        upload_destination: '%kernel.project_dir%/public/uploads/userPictures'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
